# Generated by Django 5.0.1 on 2024-01-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='latidude',
            new_name='latitude',
        ),
    ]
